app:
  name: my-app
  image: nginx:latest

service:
  type: ClusterIP
  port: 80
  targetPort: 8080
  annotations: {}

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  cpuTarget: 80
  memoryTarget: 70

keda:
  enabled: true

  minReplicaCount: 1
  maxReplicaCount: 10
  pollingInterval: 30
  cooldownPeriod: 300

  triggers:
    cpu:
      enabled: true
      target: "75"

    memory:
      enabled: true
      target: "80"

    kafka:
      enabled: true
      bootstrapServers: kafka.default.svc:9092
      topic: test-topic
      consumerGroup: test-consumer-group
      lagThreshold: 10
      auth:
        authMode: "sasl_plaintext"