{{- if .Values.keda.triggers.kafka.auth }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app.name }}-kafka-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  authMode: {{ .Values.keda.triggers.kafka.auth.authMode | quote }}
  username: {{ .Values.keda.triggers.kafka.auth.username | quote }}
  password: {{ .Values.keda.triggers.kafka.auth.password | quote }}
  {{- if .Values.keda.triggers.kafka.auth.ca }}
  ca: {{ .Values.keda.triggers.kafka.auth.ca | quote }}
  {{- end }}
  {{- if .Values.keda.triggers.kafka.auth.cert }}
  cert: {{ .Values.keda.triggers.kafka.auth.cert | quote }}
  {{- end }}
  {{- if .Values.keda.triggers.kafka.auth.key }}
  key: {{ .Values.keda.triggers.kafka.auth.key | quote }}
  {{- end }}
{{- end }}